In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [5]:
!conda install -c conda-forge nibabel -y

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

# Analysing TADPOLE  files

In [7]:
df_tadpole_d1d2 = pd.read_csv('tadpole_challenge/TADPOLE_D1_D2.csv')
df_tadpole_d1d2.sort_values("RID",inplace=True)
df_tadpole_d1d2.shape

/home/lucasthim/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (471,473,474,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,569,570,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,599,601,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,624,625,626,627,628,629,630,631,632,633,634,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,745,746,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,770,771,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,794,795,797,798,799,800,801,802,803,804,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

(12741, 1907)

In [8]:
df_tadpole_d1d2dict = pd.read_csv('tadpole_challenge/TADPOLE_D1_D2_Dict.csv')[["FLDNAME","TBLNAME","CRFNAME","TEXT","NOTES"]]
df_tadpole_d1d2dict.shape

(1918, 5)

In [9]:
df_tadpole_d1d2

,RID,PTID,VISCODE,SITE,D1,D2,COLPROT,ORIGPROT,EXAMDATE,DX_bl,DXCHANGE,AGE,PTGENDER,PTEDUCAT,PTETHCAT,PTRACCAT,PTMARRY,APOE4,FDG,PIB,AV45,CDRSB,ADAS11,ADAS13,MMSE,RAVLT_immediate,RAVLT_learning,RAVLT_forgetting,RAVLT_perc_forgetting,FAQ,MOCA,EcogPtMem,EcogPtLang,EcogPtVisspat,EcogPtPlan,EcogPtOrgan,EcogPtDivatt,EcogPtTotal,EcogSPMem,EcogSPLang,EcogSPVisspat,EcogSPPlan,EcogSPOrgan,EcogSPDivatt,EcogSPTotal,FLDSTRENG,FSVERSION,Ventricles,Hippocampus,WholeBrain,...,AD_SCR_R_DTIROI_04_30_14,AD_PCR_L_DTIROI_04_30_14,AD_PCR_R_DTIROI_04_30_14,AD_CGC_L_DTIROI_04_30_14,AD_CGC_R_DTIROI_04_30_14,AD_CGH_L_DTIROI_04_30_14,AD_CGH_R_DTIROI_04_30_14,AD_FX_ST_L_DTIROI_04_30_14,AD_FX_ST_R_DTIROI_04_30_14,AD_SLF_L_DTIROI_04_30_14,AD_SLF_R_DTIROI_04_30_14,AD_SFO_L_DTIROI_04_30_14,AD_SFO_R_DTIROI_04_30_14,AD_IFO_L_DTIROI_04_30_14,AD_IFO_R_DTIROI_04_30_14,AD_SS_L_DTIROI_04_30_14,AD_SS_R_DTIROI_04_30_14,AD_EC_L_DTIROI_04_30_14,AD_EC_R_DTIROI_04_30_14,AD_UNC_L_DTIROI_04_30_14,AD_UNC_R_DTIROI_04_30_14,AD_FX_L_DTIROI_04_30_14,AD_FX_R_DTIROI_04_30_14,AD_GCC_L_DTIROI_04_30_14,AD_GCC_R_DTIROI_04_30_14,AD_BCC_L_DTIROI_04_30_14,AD_BCC_R_DTIROI_04_30_14,AD_SCC_L_DTIROI_04_30_14,AD_SCC_R_DTIROI_04_30_14,AD_RLIC_L_DTIROI_04_30_14,AD_RLIC_R_DTIROI_04_30_14,AD_TAP_L_DTIROI_04_30_14,AD_TAP_R_DTIROI_04_30_14,AD_SUMGCC_DTIROI_04_30_14,AD_SUMBCC_DTIROI_04_30_14,AD_SUMSCC_DTIROI_04_30_14,AD_SUMCC_DTIROI_04_30_14,AD_SUMFX_DTIROI_04_30_14,update_stamp_DTIROI_04_30_14,EXAMDATE_UPENNBIOMK9_04_19_17,PHASE_UPENNBIOMK9_04_19_17,BATCH_UPENNBIOMK9_04_19_17,KIT_UPENNBIOMK9_04_19_17,STDS_UPENNBIOMK9_04_19_17,RUNDATE_UPENNBIOMK9_04_19_17,ABETA_UPENNBIOMK9_04_19_17,TAU_UPENNBIOMK9_04_19_17,PTAU_UPENNBIOMK9_04_19_17,COMMENT_UPENNBIOMK9_04_19_17,update_stamp_UPENNBIOMK9_04_19_17
0,2,011_S_0002,bl,11,1,1,ADNI1,ADNI1,2005-09-08,CN,1.0,74.3,Male,16,Not Hisp/Latino,White,Married,0.0,1.36926,NaN,NaN,0.0,10.67,18.67,28.0,44.0,4.0,6.0,54.5455,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5 Tesla MRI,Cross-Sectional FreeSurfer (FreeSurfer Version...,118233.0,8336.0,1229740.0,...,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
11959,2,011_S_0002,m120,11,1,1,ADNI2,ADNI1,2015-09-22,CN,1.0,74.3,Male,16,Not Hisp/Latino,White,Married,0.0,NaN,NaN,NaN,0.0,11.00,19.00,28.0,34.0,5.0,8.0,80.0000,0.0,22.0,2.000,1.55556,1.14286,1.2,1.66667,1.75000,1.56410,1.28571,1.44444,1.00000,1.0,1.50000,1.25,1.28571,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
11571,2,011_S_0002,m108,11,1,1,ADNI2,ADNI1,2014-10-13,CN,NaN,74.3,Male,16,Not Hisp/Latino,White,Married,0.0,NaN,NaN,NaN,0.0,NaN,NaN,28.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
10836,2,011_S_0002,m102,11,1,1,ADNI2,ADNI1,2014-03-17,CN,NaN,74.3,Male,16,Not Hisp/Latino,White,Married,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
5731,2,011_S_0002,m96,11,1,1,ADNI2,ADNI1,2013-09-09,CN,1.0,74.3,Male,16,Not Hisp/Latino,White,Married,0.0,NaN,NaN,NaN,0.5,10.00,18.00,25.0,38.0,3.0,6.0,66.6667,0.0,20.0,2.125,1.44444,1.57143,1.0,1.16667,1.50000,1.51282,1.12500,1.44444,1.00000,1.0,1.16667,1.00,1.15385,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12277,5295,057_S_5295,m24,57,1,1,ADNI2,ADNI2,2015-12-08,SMC,1.0,75.5,Female,15,Not Hisp/Latino,White,Married,1.0,NaN,NaN,1.27419,2.0,11.00,18.00,26.0,32.0,1.0,-7.0,-116.6670,1.0,27.0,1.500,1.11111,1.14286,1.0,1.00000,1.66667,1.21053,3.75000,2.00000,2.00000,3.0,2.50000,3.00,2.67568,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
10803,5295,057_S_5295,m03,57,1,1,ADNI2,ADNI2,2014-02-14,SMC,NaN,75.5,Female,15,Not Hisp/Latino,White,Married,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
10802,5295,057_S_5295,bl,57,1,1,ADNI2,ADNI2,2013-12-11,SMC,1.0,75.5,Female,15,Not Hisp/Latino,White,Married,1.0,1.16317,NaN,1.31903,0.5,11.00,18.00,29.0,28.0,4.0,4.0,50.0000,1.0,27.0,2.250,2.22222,1.71429,1.4,2.00000,2.50000,2.02564,2.12500,1.11111,1.28571,1.8,1.80000,1.50,1.57895,3 Tesla MRI,Cross-Sectional FreeSurfer (5.1),NaN,5928.0,NaN,...,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,2013-12-17,ADNI2,UPENNBIOMK9,P06-MP02-MP01,P06-MP02-MP01/2,2017-01-13,416.8,88.69,8.53,NaN,2017-04-20 14:39:56.0
12302,5296,053_S_5296,m24,53,1,1,ADNI2,ADNI2,2015-12-17,SMC,1.0,69.3,Male,14,Not Hisp/Latino,White,Married,0.0,NaN,NaN,1.28309,0.0,12.00,15.00,29.0,40.0,6.0,4.0,40.0000,1.0,26.0,3.000,1.66667,1.00000,1.0,1.66667,2.00000,1.76923,1.62500,1.22222,1.14286,1.0,1.33333,1.25,1.28205,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
10804,5296,053_S_5296,bl,53,1,1,ADNI2,ADNI2,2013-12-18,SMC,1.0,69.3,Male,14,Not Hisp/Latino,White,Married,0.0,1.42926,NaN,1.13838,0.0,9.00,14.00,29.0,38.0,2.0,6.0,75.0000,1.0,26.0,2.875,1.88889,1.14286,1.2,1.16667,1.75000,1.74359,2.00000,1.44444,1.14286,1.0,1.33333,1.75,1.46154,3 Tesla MRI,Cross-Sectional FreeSurfer (5.1),18633.0,10602.0,1486040.0,...,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,2013-12-18,ADNI2,UPENNBIOMK9,P06-MP02-MP01,P06-MP02-MP01/2,2016-11-28,1460,224.9,20.9,NaN,2017-04-20 14:39:56.0

In [13]:
df_tadpole_d1d2.columns[:50]

Index(['RID', 'PTID', 'VISCODE', 'SITE', 'D1', 'D2', 'COLPROT', 'ORIGPROT',
       'EXAMDATE', 'DX_bl', 'DXCHANGE', 'AGE', 'PTGENDER', 'PTEDUCAT',
       'PTETHCAT', 'PTRACCAT', 'PTMARRY', 'APOE4', 'FDG', 'PIB', 'AV45',
       'CDRSB', 'ADAS11', 'ADAS13', 'MMSE', 'RAVLT_immediate',
       'RAVLT_learning', 'RAVLT_forgetting', 'RAVLT_perc_forgetting', 'FAQ',
       'MOCA', 'EcogPtMem', 'EcogPtLang', 'EcogPtVisspat', 'EcogPtPlan',
       'EcogPtOrgan', 'EcogPtDivatt', 'EcogPtTotal', 'EcogSPMem', 'EcogSPLang',
       'EcogSPVisspat', 'EcogSPPlan', 'EcogSPOrgan', 'EcogSPDivatt',
       'EcogSPTotal', 'FLDSTRENG', 'FSVERSION', 'Ventricles', 'Hippocampus',
       'WholeBrain'],
      dtype='object')

In [10]:
participant_info_cols = ['RID', 'PTID', 'VISCODE', 'SITE', 'D1', 'D2', 'COLPROT', 'ORIGPROT', 'EXAMDATE', 'DX_bl', 'DXCHANGE', 'AGE', 'PTGENDER', 'PTEDUCAT', 'PTETHCAT', 'PTRACCAT', 'PTMARRY']
df_tadpole_participant = df_tadpole_d1d2[participant_info_cols]
df_tadpole_participant.head(15)

,RID,PTID,VISCODE,SITE,D1,D2,COLPROT,ORIGPROT,EXAMDATE,DX_bl,DXCHANGE,AGE,PTGENDER,PTEDUCAT,PTETHCAT,PTRACCAT,PTMARRY
0,2,011_S_0002,bl,11,1,1,ADNI1,ADNI1,2005-09-08,CN,1.0,74.3,Male,16,Not Hisp/Latino,White,Married
11959,2,011_S_0002,m120,11,1,1,ADNI2,ADNI1,2015-09-22,CN,1.0,74.3,Male,16,Not Hisp/Latino,White,Married
11571,2,011_S_0002,m108,11,1,1,ADNI2,ADNI1,2014-10-13,CN,NaN,74.3,Male,16,Not Hisp/Latino,White,Married
10836,2,011_S_0002,m102,11,1,1,ADNI2,ADNI1,2014-03-17,CN,NaN,74.3,Male,16,Not Hisp/Latino,White,Married
5731,2,011_S_0002,m96,11,1,1,ADNI2,ADNI1,2013-09-09,CN,1.0,74.3,Male,16,Not Hisp/Latino,White,Married
5730,2,011_S_0002,m90,11,1,1,ADNI2,ADNI1,2013-03-25,CN,NaN,74.3,Male,16,Not Hisp/Latino,White,Married
5729,2,011_S_0002,m84,11,1,1,ADNI2,ADNI1,2012-09-26,CN,4.0,74.3,Male,16,Not Hisp/Latino,White,Married
5728,2,011_S_0002,m78,11,1,1,ADNI2,ADNI1,2012-03-22,CN,NaN,74.3,Male,16,Not Hisp/Latino,White,Married
5726,2,011_S_0002,m66,11,1,1,ADNIGO,ADNI1,2011-03-04,CN,NaN,74.3,Male,16,Not Hisp/Latino,White,Married
5725,2,011_S_0002,m60,11,1,1,ADNIGO,ADNI1,2010-09-22,CN,1.0,74.3,Male,16,Not Hisp/Latino,White,Married
5724,2,011_S_0002,m36,11,1,1,ADNI1,ADNI1,2008-08-27,CN,1.0,74.3,Male,16,Not Hisp/Latino,White,Married
5723,2,011_S_0002,m06,11,1,1,ADNI1,ADNI1,2006-03-06,CN,1.0,74.3,Male,16,Not Hisp/Latino,White,Married
5727,2,011_S_0002,m72,11,1,1,ADNI2,ADNI1,2011-09-19,CN,1.0,74.3,Male,16,Not Hisp/Latino,White,Married
1,3,011_S_0003,bl,11,1,0,ADNI1,ADNI1,2005-09-12,AD,3.0,81.3,Male,18,Not Hisp/Latino,White,Married
2,3,011_S_0003,m06,11,1,0,ADNI1,ADNI1,2006-03-13,AD,3.0,81.3,Male,18,Not Hisp/Latino,White,Married

In [10]:
df_tadpole_d1d2dict

,FLDNAME,TBLNAME,CRFNAME,TEXT,NOTES
0,RID,ADNIMERGE,KEY ADNI TABLES MERGED INTO ONE TABLE,PARTICIPANT ROSTER ID,THE 4 DIGIT ROSTER ID (RID) SHOULD BE USED TO ...
1,PTID,ADNIMERGE,KEY ADNI TABLES MERGED INTO ONE TABLE,PARTICIPANT ID,3 DIGIT SITE NUMBER AND 4 DIGIT ROSTER ID (RID...
2,VISCODE,ADNIMERGE,KEY ADNI TABLES MERGED INTO ONE TABLE,VISIT CODE,-4.0
3,D1,,,DENOTES WHETHER PARTICIPANT BELONGS TO DATASET D1,
4,D2,,,DENOTES WHETHER PARTICIPANT BELONGS TO DATASET D2,
...,...,...,...,...,...
1913,RUNDATE_UPENNBIOMK9_04_19_17,UPENNBIOMK9,UPENN CSF BIOMARKERS ELECSYS,DATE OF ANALYTICAL RUN,
1914,ABETA_UPENNBIOMK9_04_19_17,UPENNBIOMK9,UPENN CSF BIOMARKERS ELECSYS,RESULT,
1915,TAU_UPENNBIOMK9_04_19_17,UPENNBIOMK9,UPENN CSF BIOMARKERS ELECSYS,RESULT,
1916,PTAU_UPENNBIOMK9_04_19_17,UPENNBIOMK9,UPENN CSF BIOMARKERS ELECSYS,RESULT,
1917,COMMENT_UPENNBIOMK9_04_19_17,UPENNBIOMK9,UPENN CSF BIOMARKERS ELECSYS,COMMENT,EXTRAPOLATED ABETA RESULT

In [11]:
df_tadpole_d1d2dict["NOTES"].iloc[0]

'The 4 digit roster ID (RID) should be used to merge data'

In [12]:
df_tadpole_d1d2dict["NOTES"].iloc[1]

"3 digit site number and 4 digit roster ID (RID) separated by '_S_'"

In [13]:
for col in df_tadpole_d1d2dict.columns:
    df_tadpole_d1d2dict[col] = df_tadpole_d1d2dict[col].str.upper()

In [14]:
df_tadpole_d1d2dict.fillna(' ',inplace = True)

# Alzheimer diagnosis classes

In [15]:
df_tadpole_participant['DX_bl'].unique()

array(['CN', 'AD', 'LMCI', 'EMCI', 'SMC'], dtype=object)

In [16]:
for diagnosis in df_tadpole_participant['DX_bl'].unique():
    registers = df_tadpole_participant.query("DX_bl == @diagnosis").shape[0]
    print(f"Number of participants with diagnosis {diagnosis}: {registers}")

Number of participants with diagnosis CN: 3821
Number of participants with diagnosis AD: 1568
Number of participants with diagnosis LMCI: 4644
Number of participants with diagnosis EMCI: 2319
Number of participants with diagnosis SMC: 389

In [17]:
for diagnosis in ["CN","MCI", "AD"]:
    if diagnosis == "CN":
        diags = ['CN','SMC']
    elif diagnosis == 'MCI':
        diags = ['LMCI','EMCI']
    else: diags = ['AD']
    registers = df_tadpole_participant.query("DX_bl == @diags").shape[0]
    print(f"Number of participants with diagnosis {diagnosis}: {registers}")

Number of participants with diagnosis CN: 4210
Number of participants with diagnosis MCI: 6963
Number of participants with diagnosis AD: 1568

# Image related columns

## MRI image columns

In [57]:
df_tadpole_d1d2dict.loc[df_tadpole_d1d2dict['FLDNAME'].str.contains("UID"),:]

,FLDNAME,TBLNAME,CRFNAME,TEXT,NOTES
95,LONIUID_UCSFFSL_02_01_16_UCSFFSL51ALL_08_01_16,UCSFFSL,LONGITUDINAL FREESURFER (FREESURFER VERSION 4.4),THE LONI SERIES UID FOR THE IMAGE PROCESSED.,-4
96,IMAGEUID_UCSFFSL_02_01_16_UCSFFSL51ALL_08_01_16,UCSFFSL,LONGITUDINAL FREESURFER (FREESURFER VERSION 4.4),THE IMAGEUID FOR THE IMAGE PROCESSED.,-4
470,LONIUID_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,UCSFFSX,CROSS-SECTIONAL FREESURFER (FREESURFER VERSION...,THE LONI SERIES UID FOR THE IMAGE PROCESSED.,-4
471,IMAGEUID_UCSFFSX_11_02_15_UCSFFSX51_08_01_16,UCSFFSX,CROSS-SECTIONAL FREESURFER (FREESURFER VERSION...,THE IMAGEUID FOR THE IMAGE PROCESSED.,-4
835,LONIUID_BAIPETNMRC_09_12_16,BAIPETNMRC,BANNER ALZHEIMER'S INSTITUTE PET NMRC SUMMARIES,LONI UNIQUE IMAGE IDENTIFIER,THIS IS A LONGER DESCRIPTION IF NECESSARY.
1670,LONIUID_1_DTIROI_04_30_14,DTIROI,DTI ROI SUMMARY MEASURES,LONI IMAGE ID FOR FA,
1671,LONIUID_2_DTIROI_04_30_14,DTIROI,DTI ROI SUMMARY MEASURES,LONI IMAGE ID FOR MD,
1672,LONIUID_3_DTIROI_04_30_14,DTIROI,DTI ROI SUMMARY MEASURES,LONI IMAGE ID FOR RD,
1673,LONIUID_4_DTIROI_04_30_14,DTIROI,DTI ROI SUMMARY MEASURES,LONI IMAGE ID FOR AD,

In [72]:
mri_images_ids = ['IMAGEUID_UCSFFSL_02_01_16_UCSFFSL51ALL_08_01_16','IMAGEUID_UCSFFSX_11_02_15_UCSFFSX51_08_01_16']

In [91]:
df_check_nulls = (df_tadpole_d1d2 != ' ')
df_mri = df_tadpole_d1d2[df_check_nulls[mri_images_ids].any(axis = 1)][participant_info_cols + mri_images_ids]
df_mri

,RID,PTID,VISCODE,SITE,D1,D2,COLPROT,ORIGPROT,EXAMDATE,DX_bl,DXCHANGE,AGE,PTGENDER,PTEDUCAT,PTETHCAT,PTRACCAT,PTMARRY,IMAGEUID_UCSFFSL_02_01_16_UCSFFSL51ALL_08_01_16,IMAGEUID_UCSFFSX_11_02_15_UCSFFSX51_08_01_16
0,2,011_S_0002,bl,11,1,1,ADNI1,ADNI1,2005-09-08,CN,1.0,74.3,Male,16,Not Hisp/Latino,White,Married,,35475
1,3,011_S_0003,bl,11,1,0,ADNI1,ADNI1,2005-09-12,AD,3.0,81.3,Male,18,Not Hisp/Latino,White,Married,32237,32237
2,3,011_S_0003,m06,11,1,0,ADNI1,ADNI1,2006-03-13,AD,3.0,81.3,Male,18,Not Hisp/Latino,White,Married,,31863
3,3,011_S_0003,m12,11,1,0,ADNI1,ADNI1,2006-09-12,AD,3.0,81.3,Male,18,Not Hisp/Latino,White,Married,35576,35576
4,3,011_S_0003,m24,11,1,0,ADNI1,ADNI1,2007-09-12,AD,3.0,81.3,Male,18,Not Hisp/Latino,White,Married,,88252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12276,5292,057_S_5292,m24,57,1,1,ADNI2,ADNI2,2015-11-19,SMC,1.0,74.3,Female,13,Not Hisp/Latino,White,Married,570688,570688
5588,5292,057_S_5292,bl,57,1,1,ADNI2,ADNI2,2013-11-12,SMC,1.0,74.3,Female,13,Not Hisp/Latino,White,Married,398341,398341
5587,5294,051_S_5294,bl,51,1,1,ADNI2,ADNI2,2013-11-25,SMC,1.0,68.5,Male,18,Not Hisp/Latino,White,Divorced,,398094
10802,5295,057_S_5295,bl,57,1,1,ADNI2,ADNI2,2013-12-11,SMC,1.0,75.5,Female,15,Not Hisp/Latino,White,Married,,402028
10804,5296,053_S_5296,bl,53,1,1,ADNI2,ADNI2,2013-12-18,SMC,1.0,69.3,Male,14,Not Hisp/Latino,White,Married,,416077

In [98]:
participants_with_mri = df_mri['PTID'].unique()
print('Patients with MRI images:' ,participants_with_mri.shape[0])
participants_with_mri

Patients with MRI images: 1735

array(['011_S_0002', '011_S_0003', '022_S_0004', ..., '051_S_5294',
       '057_S_5295', '053_S_5296'], dtype=object)

## PET images

In [18]:
# df_tadpole_d1d2dict.loc[df_tadpole_d1d2dict['FLDNAME'].str.contains("PET") & df_tadpole_d1d2dict['TEXT'].str.contains("IMAGE"),:]
df_tadpole_d1d2dict.loc[df_tadpole_d1d2dict['FLDNAME'].str.contains("PET") & df_tadpole_d1d2dict['TEXT'].str.contains("IMAGE"),:]

,FLDNAME,TBLNAME,CRFNAME,TEXT,NOTES
835,LONIUID_BAIPETNMRC_09_12_16,BAIPETNMRC,BANNER ALZHEIMER'S INSTITUTE PET NMRC SUMMARIES,LONI UNIQUE IMAGE IDENTIFIER,THIS IS A LONGER DESCRIPTION IF NECESSARY.

In [19]:
pet_images_ids = ['LONIUID_BAIPETNMRC_09_12_16']

In [20]:
df_tadpole_d1d2dict.loc[(df_tadpole_d1d2dict['TEXT'].str.contains("IMAGE")) & (~df_tadpole_d1d2dict['FLDNAME'].str.contains("UCSFF") ),:]

,FLDNAME,TBLNAME,CRFNAME,TEXT,NOTES
835,LONIUID_BAIPETNMRC_09_12_16,BAIPETNMRC,BANNER ALZHEIMER'S INSTITUTE PET NMRC SUMMARIES,LONI UNIQUE IMAGE IDENTIFIER,THIS IS A LONGER DESCRIPTION IF NECESSARY.
1670,LONIUID_1_DTIROI_04_30_14,DTIROI,DTI ROI SUMMARY MEASURES,LONI IMAGE ID FOR FA,
1671,LONIUID_2_DTIROI_04_30_14,DTIROI,DTI ROI SUMMARY MEASURES,LONI IMAGE ID FOR MD,
1672,LONIUID_3_DTIROI_04_30_14,DTIROI,DTI ROI SUMMARY MEASURES,LONI IMAGE ID FOR RD,
1673,LONIUID_4_DTIROI_04_30_14,DTIROI,DTI ROI SUMMARY MEASURES,LONI IMAGE ID FOR AD,

In [22]:
df_tadpole_d1d2dict.loc[(df_tadpole_d1d2dict['FLDNAME'].str.contains('UCBERK') ),:].head(20)

,FLDNAME,TBLNAME,CRFNAME,TEXT,NOTES
1172,FLDNAME_UCBERKELEYAV45_10_17_16,TBLNAME,CRFNAME,TEXT,NOTES
1173,RID_UCBERKELEYAV45_10_17_16,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,PARTICIPANT ROSTER ID,THE 4 DIGIT ROSTER ID (RID) SHOULD BE USED TO ...
1174,VISCODE_UCBERKELEYAV45_10_17_16,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,VISIT CODE,
1175,VISCODE2_UCBERKELEYAV45_10_17_16,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,TRANSLATED VISIT CODE,MONTHS FROM BASELINE ROUNDED TO NEAREST 6 MONTHS
1176,EXAMDATE_UCBERKELEYAV45_10_17_16,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,DATE OF AV45 SCAN,-4
1177,CEREBELLUMGREYMATTER_UCBERKELEYAV45_10_17_16,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,REFERENCE REGION - FLORBETAPIR MEAN OF CEREBEL...,-4
1178,WHOLECEREBELLUM_UCBERKELEYAV45_10_17_16,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,REFERENCE REGION - FLORBETAPIR MEAN OF WHOLE C...,-4
1179,ERODED_SUBCORTICALWM_UCBERKELEYAV45_10_17_16,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,REFERENCE REGION - FLORBETAPIR MEAN OF ERODED ...,-4
1180,COMPOSITE_REF_UCBERKELEYAV45_10_17_16,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,REFERENCE REGION - FLORBETAPIR MEAN OF COMPOSI...,-4
1181,FRONTAL_UCBERKELEYAV45_10_17_16,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,WEIGHTED FLORBETAPIR MEAN IN FRONTAL REGIONS. ...,-4
1182,CINGULATE_UCBERKELEYAV45_10_17_16,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,WEIGHTED FLORBETAPIR MEAN IN ANTERIOR/POSTERIO...,-4
1183,PARIETAL_UCBERKELEYAV45_10_17_16,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,WEIGHTED FLORBETAPIR MEAN IN LATERAL PARIETAL ...,-4
1184,TEMPORAL_UCBERKELEYAV45_10_17_16,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,WEIGHTED FLORBETAPIR MEAN IN LATERAL TEMPORAL ...,-4
1185,SUMMARYSUVR_WHOLECEREBNORM_UCBERKELEYAV45_10_1...,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,SUMMARY FLORBETAPIR CORTICAL SUVR NORMALIZED B...,-4
1186,SUMMARYSUVR_WHOLECEREBNORM_1.11CUTOFF_UCBERKEL...,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,AMYLOID POSITIVITY DETERMINED BY APPLYING A CU...,-4
1187,SUMMARYSUVR_COMPOSITE_REFNORM_UCBERKELEYAV45_1...,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,SUMMARY FLORBETAPIR CORTICAL SUVR NORMALIZED B...,-4
1188,SUMMARYSUVR_COMPOSITE_REFNORM_0.79CUTOFF_UCBER...,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,AMYLOID POSITIVITY DETERMINED BY APPLYING A CU...,-4
1189,BRAINSTEM_UCBERKELEYAV45_10_17_16,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,REFERENCE REGION - FLORBETAPIR MEAN OF BRAINST...,-4
1190,BRAINSTEM_SIZE_UCBERKELEYAV45_10_17_16,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,BRAIN-STEM ROI SIZE IN MM^3,-4
1191,VENTRICLE_3RD_UCBERKELEYAV45_10_17_16,UCBERKELEYAV45,UC BERKELEY - AV45 ANALYSIS,3RD-VENTRICLE,-4

In [23]:
df_tadpole_participant.loc[df_tadpole_d1d2['LONIUID_BAIPETNMRC_09_12_16'] != ' '].iloc[:10]

,RID,PTID,VISCODE,SITE,D1,D2,COLPROT,ORIGPROT,EXAMDATE,DX_bl,DXCHANGE,AGE,PTGENDER,PTEDUCAT,PTETHCAT,PTRACCAT,PTMARRY
0,2,011_S_0002,bl,11,1,1,ADNI1,ADNI1,2005-09-08,CN,1.0,74.3,Male,16,Not Hisp/Latino,White,Married
5723,2,011_S_0002,m06,11,1,1,ADNI1,ADNI1,2006-03-06,CN,1.0,74.3,Male,16,Not Hisp/Latino,White,Married
1,3,011_S_0003,bl,11,1,0,ADNI1,ADNI1,2005-09-12,AD,3.0,81.3,Male,18,Not Hisp/Latino,White,Married
2,3,011_S_0003,m06,11,1,0,ADNI1,ADNI1,2006-03-13,AD,3.0,81.3,Male,18,Not Hisp/Latino,White,Married
3,3,011_S_0003,m12,11,1,0,ADNI1,ADNI1,2006-09-12,AD,3.0,81.3,Male,18,Not Hisp/Latino,White,Married
4,3,011_S_0003,m24,11,1,0,ADNI1,ADNI1,2007-09-12,AD,3.0,81.3,Male,18,Not Hisp/Latino,White,Married
12,5,011_S_0005,m12,11,1,0,ADNI1,ADNI1,2006-09-05,CN,1.0,73.7,Male,16,Not Hisp/Latino,White,Married
13,5,011_S_0005,m24,11,1,0,ADNI1,ADNI1,2007-09-07,CN,1.0,73.7,Male,16,Not Hisp/Latino,White,Married
10,5,011_S_0005,bl,11,1,0,ADNI1,ADNI1,2005-09-07,CN,1.0,73.7,Male,16,Not Hisp/Latino,White,Married
11,5,011_S_0005,m06,11,1,0,ADNI1,ADNI1,2006-03-09,CN,1.0,73.7,Male,16,Not Hisp/Latino,White,Married

In [24]:
cols_d1d2 = df_tadpole_d1d2.columns.to_list()
mri_code = "UCSFFSL"
filtered_mri_cols = [x for x in cols_d1d2 if mri_code in x]
pet_filtered_cols = [x for x in df_tadpole_d1d2.columns if ("PET" in x) or ("UCBERKELE" in x)]